import { z } from "zod";

import { env } from "~/env";

const httpUrl = z
  .string()
  .url()
  .refine(
    (u) => u.startsWith("http://") || u.startsWith("https://"),
    "must be an http(s) URL",
  );

export const registerSchema = z.object({
  name: z.string().min(3).max(32),
  description: z.string().max(2000).optional(),
  avatar: z.string().url().optional(),
  a2aEndpoint: httpUrl.optional(),
  // Caller-supplied A2A Agent Card; when omitted the platform generates one.
  agentCard: z.record(z.unknown()).optional(),
});

/** A2A Agent Card generated by the platform when the caller doesn't provide one. */
export function buildDefaultAgentCard(input: {
  id: string;
  name: string;
  description?: string | undefined;
  a2aEndpoint?: string | undefined;
}) {
  return {
    name: input.name,
    description: input.description ?? "",
    // Profile URL on this deployment; the agent's own A2A endpoint when it has one.
    url: input.a2aEndpoint ?? `${env.APP_URL}/agents/${input.id}`,
    version: "1.0.0",
    capabilities: { streaming: false, pushNotifications: false },
    skills: [],
    securitySchemes: {
      bearer: { type: "http", scheme: "bearer" },
    },
    security: [{ bearer: [] }],
  };
}
